name: Latest blog post workflow
on:
  push:
    branches:
      - main
  schedule: # Run workflow automatically
    - cron: '0 0 * * *' # Runs every hour, on the hour
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the Github Actions Workflow page directly

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Pull in sspai.com posts
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: SSPAI
          feed_list: "https://sspai.com/feed"
      - name: Pull in appinn.com posts
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: APPINN
          feed_list: "https://feeds.appinn.com/appinns"
      #     - name: Pull in bilibili posts
      #       uses: gautamkrishnar/blog-post-workflow@master
      #        with:
      #          comment_tag_name: BILIBILI
      #         feed_list: "https://rsshub-gsyx.vercel.app/bilibili/ranking/0/3?limit=10"

  #      - uses: gautamkrishnar/blog-post-workflow@master
  #       with:
  #          comment_tag_name: MEDIUM
#           feed_list: "https://medium.com/feed/@khaosdoctor"